"""create_conversation_persistence

Revision ID: 28d73d938a65
Revises:
Create Date: 2026-07-09 12:30:57.767413

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "28d73d938a65"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("model_profile", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("forked_from_id", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["forked_from_id"], ["sessions.id"], name=op.f("fk_sessions_forked_from_id_sessions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("id", "model_profile", name="uq_sessions_id_model_profile"),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.String(length=255), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("model_profile", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["messages.id"], name=op.f("fk_messages_parent_id_messages")
        ),
        sa.ForeignKeyConstraint(
            ["session_id", "model_profile"],
            ["sessions.id", "sessions.model_profile"],
            name="fk_messages_session_id_model_profile_sessions",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_table(
        "compaction_markers",
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"], ["messages.id"], name=op.f("fk_compaction_markers_message_id_messages")
        ),
        sa.PrimaryKeyConstraint("message_id", name=op.f("pk_compaction_markers")),
    )
    # ### end Alembic commands ###

    # Set up manually defined triggers for append-only behavior
    op.execute(
        """
        CREATE OR REPLACE FUNCTION prevent_update_or_delete()
        RETURNS TRIGGER AS $$
        BEGIN
            RAISE EXCEPTION 'Table is append-only. UPDATE and DELETE are not allowed.';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER prevent_update_delete_messages
        BEFORE UPDATE OR DELETE ON messages
        FOR EACH ROW
        EXECUTE FUNCTION prevent_update_or_delete();
        """
    )
    op.execute(
        """
        CREATE TRIGGER prevent_update_delete_compaction_markers
        BEFORE UPDATE OR DELETE ON compaction_markers
        FOR EACH ROW
        EXECUTE FUNCTION prevent_update_or_delete();
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Clean up manually defined triggers and function
    op.execute("DROP TRIGGER IF EXISTS prevent_update_delete_messages ON messages;")
    op.execute(
        "DROP TRIGGER IF EXISTS prevent_update_delete_compaction_markers ON compaction_markers;"
    )
    op.execute("DROP FUNCTION IF EXISTS prevent_update_or_delete();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("compaction_markers")
    op.drop_table("messages")
    op.drop_table("sessions")
    # ### end Alembic commands ###
