"""create_identity_schema

Revision ID: 724789ea8df4
Revises: ddacc8ae120e
Create Date: 2026-07-09 18:40:58.823619

Crea el esquema de identidad y acceso (d11, sección 1): usuarios, sesiones de
identidad, TOTP, intentos de login, grupos, acuerdo de uso y auditoría de
identidad.

Desvíos documentados:
- La tabla de sesiones de identidad se llama ``auth_sessions`` (no ``sessions``):
  ``sessions`` ya está tomada por las sesiones de conversación de b04.
- La auditoría de identidad usa una tabla propia ``identity_audit_events`` (no
  ``audit_logs`` de b04, que es Policy-Gate-shaped) con el MISMO mecanismo
  append-only: el trigger ``prevent_update_or_delete()`` creado en la primera
  migración de b04.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "724789ea8df4"
down_revision: str | Sequence[str] | None = "ddacc8ae120e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # `users.username` es CITEXT (unicidad case-insensitive nativa): la extensión
    # debe existir antes de crear la tabla.
    op.execute("CREATE EXTENSION IF NOT EXISTS citext;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_groups")),
        sa.UniqueConstraint("name", name=op.f("uq_groups_name")),
    )
    op.create_table(
        "login_attempts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_ref", sa.String(length=255), nullable=False),
        sa.Column("origin", sa.String(length=255), nullable=False),
        sa.Column("failed_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_login_attempts")),
    )
    op.create_index(
        "ix_login_attempts_account_ref_failed_at",
        "login_attempts",
        ["account_ref", "failed_at"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", postgresql.CITEXT(), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("preferred_language", sa.String(length=10), nullable=True),
        sa.Column("preferred_theme", sa.String(length=20), nullable=True),
        sa.Column("totp_required", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("role IN ('admin', 'tecnico', 'funcional')", name=op.f("ck_users_role")),
        sa.CheckConstraint(
            "status IN ('active', 'suspended', 'deactivated')", name=op.f("ck_users_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["revoked_by"], ["users.id"], name=op.f("fk_auth_sessions_revoked_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_auth_sessions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_sessions")),
    )
    op.create_index("ix_auth_sessions_expires_at", "auth_sessions", ["expires_at"], unique=False)
    op.create_index("ix_auth_sessions_user_id", "auth_sessions", ["user_id"], unique=False)
    op.create_table(
        "group_members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("added_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name=op.f("fk_group_members_group_id_groups")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_group_members_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_group_members")),
        sa.UniqueConstraint("group_id", "user_id", name="uq_group_members_group_id_user_id"),
    )
    op.create_table(
        "identity_audit_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("target_ref", sa.String(length=255), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_identity_audit_events_actor_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identity_audit_events")),
    )
    op.create_table(
        "totp_backup_codes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("code_hash", sa.String(length=255), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_totp_backup_codes_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_totp_backup_codes")),
    )
    op.create_index("ix_totp_backup_codes_user_id", "totp_backup_codes", ["user_id"], unique=False)
    op.create_table(
        "totp_secrets",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("encrypted_secret", sa.LargeBinary(), nullable=False),
        sa.Column("enrolled_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_totp_secrets_user_id_users")
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_totp_secrets")),
    )
    op.create_table(
        "usage_agreement_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=False),
        sa.Column("published_by", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["published_by"],
            ["users.id"],
            name=op.f("fk_usage_agreement_versions_published_by_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_agreement_versions")),
        sa.UniqueConstraint(
            "version_number", name=op.f("uq_usage_agreement_versions_version_number")
        ),
    )
    op.create_table(
        "usage_agreement_acceptances",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_usage_agreement_acceptances_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["usage_agreement_versions.id"],
            name=op.f("fk_usage_agreement_acceptances_version_id_usage_agreement_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_agreement_acceptances")),
        sa.UniqueConstraint(
            "user_id",
            "version_id",
            name="uq_usage_agreement_acceptances_user_id_version_id",
        ),
    )
    # ### end Alembic commands ###

    # `identity_audit_events` es append-only: reutiliza la función
    # `prevent_update_or_delete()` creada por la primera migración de b04 (mismo
    # mecanismo que `audit_logs`, `messages`, etc.). Bloquea UPDATE y DELETE.
    op.execute(
        """
        CREATE TRIGGER prevent_update_delete_identity_audit_events
        BEFORE UPDATE OR DELETE ON identity_audit_events
        FOR EACH ROW
        EXECUTE FUNCTION prevent_update_or_delete();
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        "DROP TRIGGER IF EXISTS prevent_update_delete_identity_audit_events "
        "ON identity_audit_events;"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("usage_agreement_acceptances")
    op.drop_table("usage_agreement_versions")
    op.drop_table("totp_secrets")
    op.drop_index("ix_totp_backup_codes_user_id", table_name="totp_backup_codes")
    op.drop_table("totp_backup_codes")
    op.drop_table("identity_audit_events")
    op.drop_table("group_members")
    op.drop_index("ix_auth_sessions_user_id", table_name="auth_sessions")
    op.drop_index("ix_auth_sessions_expires_at", table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_table("users")
    op.drop_index("ix_login_attempts_account_ref_failed_at", table_name="login_attempts")
    op.drop_table("login_attempts")
    op.drop_table("groups")
    # ### end Alembic commands ###
    # La extensión citext se deja instalada a propósito (es idempotente y podría
    # ser usada por otros objetos; eliminarla no aporta y arriesga el downgrade).
