"""create_audit_log

Revision ID: b61b5986c3eb
Revises: c6a9321d50ac
Create Date: 2026-07-09 12:36:20.641049

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b61b5986c3eb"
down_revision: str | Sequence[str] | None = "c6a9321d50ac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user", sa.String(length=255), nullable=False),
        sa.Column("tenant", sa.String(length=255), nullable=True),
        sa.Column("agent", sa.String(length=255), nullable=False),
        sa.Column("skill", sa.String(length=255), nullable=False),
        sa.Column("tool", sa.String(length=255), nullable=False),
        sa.Column("operation_type", sa.String(length=50), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("environment", sa.String(length=255), nullable=False),
        sa.Column("effect", sa.String(length=50), nullable=False),
        sa.Column("applied_policy", sa.String(length=255), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("corrects", sa.UUID(), nullable=True),
        sa.Column("result_summary", sa.Text(), nullable=True),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("trace_id", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["corrects"], ["audit_logs.id"], name=op.f("fk_audit_logs_corrects_audit_logs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    # ### end Alembic commands ###

    op.execute(
        """
        CREATE TRIGGER prevent_update_delete_audit_logs
        BEFORE UPDATE OR DELETE ON audit_logs
        FOR EACH ROW
        EXECUTE FUNCTION prevent_update_or_delete();
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS prevent_update_delete_audit_logs ON audit_logs;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
