"""create_attachment_storage

Revision ID: c6a9321d50ac
Revises: 28d73d938a65
Create Date: 2026-07-09 12:33:41.032430

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c6a9321d50ac"
down_revision: str | Sequence[str] | None = "28d73d938a65"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "extractions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant", sa.String(length=255), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("full_text", sa.Text(), nullable=False),
        sa.Column("extractor_version", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extractions")),
        sa.UniqueConstraint("tenant", "sha256", name="uq_extractions_tenant_sha256"),
    )
    op.create_table(
        "attachments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.Column("message_id", sa.UUID(), nullable=True),
        sa.Column("uploaded_by", sa.String(length=255), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("declared_mime", sa.String(length=255), nullable=False),
        sa.Column("detected_type", sa.String(length=255), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_path", sa.UUID(), nullable=True),
        sa.Column("scan_result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("tenant", sa.String(length=255), nullable=False),
        sa.Column("extraction_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "status IN ('uploaded', 'extracting', 'ready', 'blocked', 'error')",
            name=op.f("ck_attachments_status"),
        ),
        sa.ForeignKeyConstraint(
            ["extraction_id"],
            ["extractions.id"],
            ondelete="SET NULL",
            name=op.f("fk_attachments_extraction_id_extractions"),
        ),
        sa.ForeignKeyConstraint(
            ["message_id"], ["messages.id"], name=op.f("fk_attachments_message_id_messages")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["sessions.id"], name=op.f("fk_attachments_session_id_sessions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachments")),
    )
    op.create_table(
        "message_attachments",
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("attachment_id", sa.UUID(), nullable=False),
        sa.Column("inserted_text", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("truncated", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attachment_id"],
            ["attachments.id"],
            name=op.f("fk_message_attachments_attachment_id_attachments"),
        ),
        sa.ForeignKeyConstraint(
            ["message_id"], ["messages.id"], name=op.f("fk_message_attachments_message_id_messages")
        ),
        sa.PrimaryKeyConstraint("message_id", "attachment_id", name=op.f("pk_message_attachments")),
    )
    # ### end Alembic commands ###

    # Set up manually defined trigger for append-only behavior on message_attachments
    op.execute(
        """
        CREATE TRIGGER prevent_update_delete_message_attachments
        BEFORE UPDATE OR DELETE ON message_attachments
        FOR EACH ROW
        EXECUTE FUNCTION prevent_update_or_delete();
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Clean up manually defined trigger
    op.execute(
        "DROP TRIGGER IF EXISTS prevent_update_delete_message_attachments ON message_attachments;"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message_attachments")
    op.drop_table("attachments")
    op.drop_table("extractions")
    # ### end Alembic commands ###
